export const LOGIN_SEND_CREDENTIALS = 'LOGIN_SEND_CREDENTIALS';
export const LOGIN_RECEIVE_RESPONSE = 'LOGIN_RECEIVE_RESPONSE';
export const LOGIN_RESET_STATE = 'LOGIN_RESET_STATE';
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT';

export const SCOREBOARD_SET_BUSY_STATE = 'SCOREBOARD_SET_BUSY_STATE';
export const SCOREBOARD_RECEIVE_PLAYERPARTICIPATION = 'SCOREBOARD_RECEIVE_PLAYERPARTICIPATION';
export const SCOREBOARD_RECEIVE_FURSUITPARTICIPATION = 'SCOREBOARD_RECEIVE_FURSUITPARTICIPATION';

export const PLAYERPARTICIPATION_QUERY = 'PLAYERPARTICIPATION_QUERY';
export const PLAYERPARTICIPATION_RECEIVE_RESPONSE = 'PLAYERPARTICIPATION_RECEIVE_RESPONSE';

export const GAME_SET_BUSY_STATE = 'GAME_SET_BUSY_STATE'
export const GAME_ASK_FOR_TOKEN = 'GAME_ASK_FOR_TOKEN'
export const GAME_COLLECT_TOKEN = 'GAME_COLLECT_TOKEN'
export const GAME_COLLECT_TOKEN_SUCCESS = 'GAME_COLLECT_TOKEN_SUCCESS'
export const GAME_COLLECT_TOKEN_FAIL = 'GAME_COLLECT_TOKEN_FAIL'

export const UI_SET_DARK_THEME = 'UI_SET_DARK_THEME'
export const UI_SET_LIGHT_THEME = 'UI_SET_LIGHT_THEME'