export const GAMESTATE_INITIALIZING = "GAMESTATE_INITIALIZING";
export const GAMESTATE_ENTER_CODE = "GAMESTATE_ENTER_CODE";
export const GAMESTATE_VERIFY_CODE_IN_PROGRESS = "GAMESTATE_VERIFY_CODE_IN_PROGRESS";
export const GAMESTATE_CATCH_SUCCESS  = "GAMESTATE_CATCH_SUCCESS";
export const GAMESTATE_CATCH_FAIL = "GAMESTATE_CATCH_FAIL";